using Microsoft.EntityFrameworkCore;
using Recruitment_Process_Management_System.Models.Entities;

namespace Recruitment_Process_Management_System.Data
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }

        public DbSet<User> Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<Candidate> Candidates { get; set; }
        public DbSet<Skill> Skills { get; set; }
        public DbSet<CandidateSkill> CandidateSkills { get; set; }

        public DbSet<Notification> Notifications { get; set; }



        // Job Position related
        public DbSet<JobPosition> JobPositions { get; set; }
        public DbSet<JobSkillRequirement> JobSkillRequirements { get; set; }
        //public DbSet<JobPositionReviewer> JobPositionReviewers { get; set; }
        public DbSet<Status> Statuses { get; set; }


        //interview related
        public DbSet<InterviewRound> InterviewRounds { get; set; }
        public DbSet<InterviewParticipant> InterviewParticipants { get; set; }
        public DbSet<InterviewFeedback> InterviewFeedbacks { get; set; }




        public DbSet<Application> Applications { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // User configuration - IMPORTANT: Configure GUID generation
            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.Id);

                // Configure GUID to be auto-generated by SQL Server
                entity.Property(e => e.Id)
                      .HasColumnType("uniqueidentifier")
                      .HasDefaultValueSql("NEWID()");

                // Configure CreatedBy as nullable GUID
                entity.Property(e => e.CreatedBy)
                      .HasColumnType("uniqueidentifier")
                      .IsRequired(false);

                // Unique email constraint
                entity.HasIndex(e => e.Email).IsUnique();
            });

            // Role configuration (keep as int - this is fine)
            modelBuilder.Entity<Role>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            // UserRole composite key configuration
            modelBuilder.Entity<UserRole>(entity =>
            {
                entity.HasKey(ur => new { ur.UserId, ur.RoleId });

                // Configure UserId as GUID
                entity.Property(e => e.UserId)
                      .HasColumnType("uniqueidentifier");

                entity.HasOne(ur => ur.User)
                      .WithMany(u => u.UserRoles)
                      .HasForeignKey(ur => ur.UserId)
                      .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(ur => ur.Role)
                      .WithMany(r => r.UserRoles)
                      .HasForeignKey(ur => ur.RoleId)
                      .OnDelete(DeleteBehavior.Cascade);
            });

            // Candidate configuration
            modelBuilder.Entity<Candidate>(entity =>
            {
                entity.HasKey(e => e.Id);

                // Configure Candidate Id as GUID
                entity.Property(e => e.Id)
                      .HasColumnType("uniqueidentifier")
                      .HasDefaultValueSql("NEWID()");

                // Configure UserId as GUID foreign key
                entity.Property(e => e.UserId)
                      .HasColumnType("uniqueidentifier");

                // Configure the foreign key relationship
                entity.HasOne(c => c.User)
                      .WithMany() // User doesn't have a collection of Candidates
                      .HasForeignKey(c => c.UserId)
                      .OnDelete(DeleteBehavior.Cascade);

                // Configure nullable columns
                entity.Property(e => e.CurrentLocation).IsRequired(false);
                entity.Property(e => e.TotalExperience).IsRequired(false);
                entity.Property(e => e.CurrentCompany).IsRequired(false);
                entity.Property(e => e.CurrentSalary).IsRequired(false);
                entity.Property(e => e.ExpectedSalary).IsRequired(false);
                entity.Property(e => e.NoticePeriod).IsRequired(false);
                entity.Property(e => e.Source).IsRequired(false);
                entity.Property(e => e.CollegeName).IsRequired(false);
                entity.Property(e => e.GraduationYear).IsRequired(false);
                entity.Property(e => e.Degree).IsRequired(false);
                entity.Property(e => e.ResumeFilePath).IsRequired(false);
            });

            // Skill configuration
            modelBuilder.Entity<Skill>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                      .HasColumnType("uniqueidentifier")
                      .HasDefaultValueSql("NEWID()");

                entity.HasIndex(e => e.SkillName).IsUnique();
            });

            // CandidateSkill configuration - THIS FIXES THE CASCADE DELETE CONFLICT
            modelBuilder.Entity<CandidateSkill>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id)
                      .HasColumnType("uniqueidentifier")
                      .HasDefaultValueSql("NEWID()");

                entity.Property(e => e.CandidateId)
                      .HasColumnType("uniqueidentifier");
                entity.Property(e => e.SkillId)
                      .HasColumnType("uniqueidentifier");


                // Unique constraint - one candidate can't have duplicate skills
                entity.HasIndex(e => new { e.CandidateId, e.SkillId })
                      .IsUnique();

                entity.HasOne(cs => cs.Candidate)
                      .WithMany(c => c.CandidateSkills)
                      .HasForeignKey(cs => cs.CandidateId)
                      .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(cs => cs.Skill)
                      .WithMany(s => s.CandidateSkills)
                      .HasForeignKey(cs => cs.SkillId)
                      .OnDelete(DeleteBehavior.Cascade);
            });

            // Seed default roles
            modelBuilder.Entity<Role>().HasData(
                new Role { Id = 1, RoleName = "Admin", IsActive = true },
                new Role { Id = 2, RoleName = "HR", IsActive = true },
                new Role { Id = 3, RoleName = "Interviewer", IsActive = true },
                new Role { Id = 4, RoleName = "Candidate", IsActive = true },
                new Role { Id = 5, RoleName = "Recruiter", IsActive = true }
            );

            modelBuilder.Entity<Status>().HasData(
                new Status { Id = 1, EntityType = "JobPosition", StatusName = "Open", IsActive = true },
                new Status { Id = 2, EntityType = "JobPosition", StatusName = "On Hold", IsActive = true },
                new Status { Id = 3, EntityType = "JobPosition", StatusName = "Closed", IsActive = true },
                new Status { Id = 4, EntityType = "Application", StatusName = "Applied", IsActive = true },
                new Status { Id = 5, EntityType = "Application", StatusName = "Screening", IsActive = true },
                new Status { Id = 6, EntityType = "Application", StatusName = "Interview", IsActive = true },
                new Status { Id = 7, EntityType = "Application", StatusName = "Selected", IsActive = true },
                new Status { Id = 8, EntityType = "Application", StatusName = "Rejected", IsActive = true },
                new Status { Id = 9, EntityType = "Interview", StatusName = "Scheduled", IsActive = true },
                new Status { Id = 10, EntityType = "Interview", StatusName = "Completed", IsActive = true },
                new Status { Id = 11, EntityType = "Interview", StatusName = "Cancelled", IsActive = true },
                new Status { Id = 12, EntityType = "Attendance", StatusName = "Present", IsActive = true },
                new Status { Id = 13, EntityType = "Attendance", StatusName = "Absent", IsActive = true },
                new Status { Id = 14, EntityType = "Attendance", StatusName = "Pending", IsActive = true }
            );


            // Application configuration
            modelBuilder.Entity<Application>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                      .HasColumnType("uniqueidentifier")
                      .HasDefaultValueSql("NEWID()");

                entity.Property(e => e.CandidateId)
                      .HasColumnType("uniqueidentifier");

                entity.Property(e => e.JobPositionId)
                      .HasColumnType("uniqueidentifier");

                // Unique constraint - one candidate can only apply once per job
                entity.HasIndex(e => new { e.CandidateId, e.JobPositionId })
                      .IsUnique();

                entity.HasOne(a => a.Candidate)
                      .WithMany()
                      .HasForeignKey(a => a.CandidateId)
                      .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(a => a.JobPosition)
                      .WithMany()
                      .HasForeignKey(a => a.JobPositionId)
                      .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(a => a.Status)
                      .WithMany()
                      .HasForeignKey(a => a.StatusId)
                      .OnDelete(DeleteBehavior.Restrict);
            });

            // InterviewRound configuration
            modelBuilder.Entity<InterviewRound>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                      .HasColumnType("uniqueidentifier")
                      .HasDefaultValueSql("NEWID()");

                entity.Property(e => e.ApplicationId)
                      .HasColumnType("uniqueidentifier");

                entity.Property(e => e.CreatedBy)
                      .HasColumnType("uniqueidentifier")
                      .IsRequired(false);

                entity.HasIndex(e => new { e.ApplicationId, e.RoundNumber })
                      .IsUnique();

                entity.HasOne(ir => ir.Application)
                      .WithMany()
                      .HasForeignKey(ir => ir.ApplicationId)
                      .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(ir => ir.Status)
                      .WithMany()
                      .HasForeignKey(ir => ir.StatusId)
                      .OnDelete(DeleteBehavior.Restrict);

                entity.HasOne(ir => ir.Creator)
                      .WithMany()
                      .HasForeignKey(ir => ir.CreatedBy)
                      .OnDelete(DeleteBehavior.Restrict);
            });

            // InterviewParticipant configuration
            modelBuilder.Entity<InterviewParticipant>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                      .HasColumnType("uniqueidentifier")
                      .HasDefaultValueSql("NEWID()");

                entity.Property(e => e.InterviewRoundId)
                      .HasColumnType("uniqueidentifier");

                entity.Property(e => e.UserId)
                      .HasColumnType("uniqueidentifier");

                entity.HasIndex(e => new { e.InterviewRoundId, e.UserId })
                      .IsUnique();

                entity.HasOne(ip => ip.InterviewRound)
                      .WithMany(ir => ir.InterviewParticipants)
                      .HasForeignKey(ip => ip.InterviewRoundId)
                      .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(ip => ip.User)
                      .WithMany()
                      .HasForeignKey(ip => ip.UserId)
                      .OnDelete(DeleteBehavior.Restrict);

                entity.HasOne(ip => ip.AttendanceStatus)
                      .WithMany()
                      .HasForeignKey(ip => ip.AttendanceStatusId)
                      .OnDelete(DeleteBehavior.Restrict);
            });

            // InterviewFeedback configuration
            modelBuilder.Entity<InterviewFeedback>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                      .HasColumnType("uniqueidentifier")
                      .HasDefaultValueSql("NEWID()");

                entity.Property(e => e.InterviewRoundId)
                      .HasColumnType("uniqueidentifier");

                entity.Property(e => e.InterviewerId)
                      .HasColumnType("uniqueidentifier");

                entity.HasIndex(e => new { e.InterviewRoundId, e.InterviewerId })
                      .IsUnique();

                entity.HasOne(f => f.InterviewRound)
                      .WithMany(ir => ir.InterviewFeedbacks)
                      .HasForeignKey(f => f.InterviewRoundId)
                      .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(f => f.Interviewer)
                      .WithMany()
                      .HasForeignKey(f => f.InterviewerId)
                      .OnDelete(DeleteBehavior.Restrict);
            });


        }
    }
}